wandb_version: 1

batch_norm:
  desc: null
  value: true
first_layer_channels:
  desc: null
  value: 32
graph_conv_layer_count:
  desc: null
  value: 6
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699118469.047092
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      - 105
      2:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
